repos:
  # Genereal pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # the release, git tag, or commit you want to use
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: [ --maxkb=1000 ]
      - id: detect-private-key
      - id: name-tests-test
        args: [ --pytest-test-first ]
      - id: fix-encoding-pragma
        args: [ --remove ]
      - id: debug-statements
        language_version: python3

  # Ruff linter hooks
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.5
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix, --show-fixes ]
        types_or: [python, pyi]
      - id: ruff-format
        types_or: [python, pyi]

  # Interrogate hooks to check code coverage
  - repo: https://github.com/econchick/interrogate
    rev: 1.7.0
    hooks:
      - id: interrogate
        exclude: 'tests/.*|docs/.*'
        args: [ --fail-under=80, --verbose ]
        additional_dependencies: [ setuptools ]

  # Numpydoc hooks to ensure numpy docstring standard
  - repo: https://github.com/numpy/numpydoc
    rev: v1.6.0
    hooks:
      - id: numpydoc-validation
        exclude: (tests|docs)/.*

  # Black code formatter hooks
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black

    # MyPy type checker hooks
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        files: ^src/
        args: [ --non-interactive, --install-types, --ignore-missing-imports ]
        additional_dependencies: [ boto3-stubs ]

    # isort hooks to sort imports
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
      - id: isort
