repos:
  # Genereal pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # the release, git tag, or commit you want to use
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Ruff linter hooks
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.5
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix, --show-fixes ]
      - id: ruff-format

  # Numpydoc hooks to ensure numpy docstring standard
  - repo: https://github.com/numpy/numpydoc
    rev: v1.6.0
    hooks:
      - id: numpydoc-validation
        exclude: (tests|docs)/.*
